#!/usr/bin/env bash
#The script Install nginx web server

#update the package list
sudo apt-get update

#Install the nginx server
sudo apt-get install -y nginx

# Start nginx 
sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.html

