#!/usr/bin/env bash

# Install Nginx
apt-get update
apt-get install -y nginx

# Configure Nginx to listen on port 80
sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Restart Nginx
kill $(cat /var/run/nginx.pid)
/usr/sbin/nginx

# Create index.html file with Hello World!
echo "Hello World!" > /var/www/html/index.html

