#!/usr/bin/env bash

# Step 1: Install Nginx
sudo apt update
sudo apt install nginx -y

# Step 2: Configure redirection using sed
sudo sed -i '/server_name _;/a \
    location \/redirect_me {\
        return 301 https:\/\/www.tutorialspoint.com\/http\/http_methods.htm;\
    }' /etc/nginx/sites-available/default

# Step 3: Reload Nginx to apply changes
sudo service nginx reload

