#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me
#is redirecting to another page.
#The redirection must be a “301 Moved Permanently”
#!/bin/bash

# Step 1: Install Nginx
sudo apt update
sudo apt install nginx -y

# Step 2: Configure redirection using sed
sudo sed -i '/server_name _;/a \
    location \/redirect_me {\
        return 301 http:\/\/google.com;\
    }' /etc/nginx/sites-available/default

# Step 3: Reload Nginx to apply changes
sudo service nginx reload

