#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.
#Configure your Nginx server so that /error_page has a custom page


# Step 1: Install Nginx
sudo apt update
sudo apt install nginx -y
ufw allow 'Nginx HTTP'


#permanent redirection
STRING="Hello World!"
REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://linkedin.com/in/jaagboku; \n\t}\n"
FILE="/etc/nginx/sites-available/default"

# Step 2: Create the custom 404 page
echo "Ceci n'est pas une page." | sudo tee /var/www/html/404.html

# Step 3: Configure Nginx to use the custom 404 page using sed
sudo sed -i '/server_name _;/a \
    error_page 404 /404.html;\
    location = /404.html {\
        internal;\
    }' /etc/nginx/sites-available/default


echo "$STRING" > /var/www/html/index.html
sed -i "37i\ $REDIRECT" "$FILE"

# Test nginx configuration for errors
sudo nginx -t

# Add custom header to the default server block
sudo sed -i '/^server {/a \ \t add_header X-Served-By $hostname;' /etc/nginx/sites-enabled/default

# Reload nginx to apply changes
sudo nginx -s reload
