#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.
#Configure your Nginx server so that /error_page has a custom page


# Step 1: Install Nginx
sudo apt update
sudo apt install nginx -y

# Step 2: Create the custom 404 page
echo "Ceci n'est pas une page." | sudo tee /var/www/html/404.html

# Step 3: Configure Nginx to use the custom 404 page using sed
sudo sed -i '/server_name _;/a \
    error_page 404 /404.html;\
    location = /404.html {\
        internal;\
    }' /etc/nginx/sites-available/default

# Step 4: Reload Nginx to apply changes
sudo service nginx restart
