#!/usr/bin/env bash
# The script installs nginx web server and configures custom HTTP response header

# Update the package list
sudo apt-get update

# Install nginx server
sudo apt-get install -y nginx

# Start nginx 
sudo service nginx start

# Add "Hello World!" to default index.html
sudo echo "Hello World!" | sudo tee -a /var/www/html/index.html

# Test nginx configuration for errors
sudo nginx -t

# Add custom header to the default server block
sudo sed -i '/^server {/a \ \t add_header X-Served-By $hostname;' /etc/nginx/sites-enabled/default

# Reload nginx to apply changes
sudo nginx -s reload
