#!/usr/bin/env bash
#The script Install nginx web server

#update the package list
sudo apt-get update

#Install the nginx server
sudo apt-get install -y nginx

# Start nginx 
sudo service nginx start

sudo echo "Hello World!"|  sudo tee -a /var/www/html/index.html

#Test configuration for error
sudo nginx -t

#Add custom header
sudo sed -i '/server {/a \\tlocation / {\n\t\tadd_header X-Served-By $hostname;\n\t}' /etc/nginx/sites-enabled/default

sudo nginx -s reload

