#!/usr/bin/env bash
#The script Install nginx web server

#update the package list
sudo apt-get update

#Install the nginx server
sudo apt-get install -y nginx

# Start nginx 
sudo service nginx start

sudo echo "Hello World!" >>  /var/www/html/index.html

#Test configuration for error
sudo nginx -t

#Add custom header
sudo nginx -q "add_header X-Served-By '$hostname'"

sudo nginx -s reload

