#!/usr/bin/env bash
# A script that creates a file /var/run/myscript.pid
#+ cntaining its PID

# create the file /var/run/myscript.pid
touch /var/run/myscript.pid

# Write th pid to the file
echo $$ > /var/run/myscript.pid

# function to cleanup when a sigterm signal is received
hate_kill ()
{
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit 0
}

trap 'hate_kill' SIGTERM SIGQUIT

# function to trap the signint signal
no_love ()
{
	echo "Y U no love me?!"
}

trap 'no_love' SIGINT

while true;
do
	echo "To infinity and beyond"
	sleep 1
done
