#!/usr/bin/env bash
# Stop bash ./4-to_infinity_and_beyond" process

target_process="bash ./4-to_infinity_and_beyond"
pid=$(pgrep -f "$target_process")

if [ -n "$pid" ];
then
	pkill -f "$target_process"
fi
