#!/usr/bin/env bash
# The sript make up a story based on /etc/passwd

passwd_file="/etc/passwd"

# Check if the file exists
if [ ! -e "$passwd_file" ];
then
	exit
fi

while IFS=":" read -r f1 f2 f3 f4 f5 f6 f7
do
	echo "The user $f1 is part of the $f4 gang, lives in $f6 rides $f7. $f3's place is protected by the passcode $f2, more info about the user here: $f5"

done < "$passwd_file"
