#!/usr/bin/env bash
# The sript make up a story based on /etc/passwd

passwd_file="/etc/passwd"

# Check if the file exists
if [ ! -e "$passwd_file" ];
then
	exit
fi

# Read the passwd file line by line using a while loop
while IFS=":" read -r username password uid gid gecos homedir shell; do
    # Display the required information
    echo "The user $username is part of the $gid gang, lives in $homedir, and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $gecos"
done < "$passwd_file"
