#!/usr/bin/env bash
# Redo task #1 in 7 lines
useradd -ms /bin/bash nginx
chown -R nginx:nginx /var/www/html /etc/nginx
sed -i 's/user www-data;/user nginx;/; s/listen 80;/listen 8080;/' /etc/nginx.conf
